export const dummyUsers = [
  {
    userId: "1",
    firstName: "John",
    lastName: "Doe",
    username: "johndoe",
    email: "john@example.com",
    password: "password123",
    isActive: true,
  },
  {
    userId: "2",
    firstName: "Jane",
    lastName: "Doe",
    username: "janedoe",
    email: "jane@example.com",
    password: "password456",
    isActive: false,
  },
  {
    userId: "3",
    firstName: "Alice",
    lastName: "Smith",
    username: "alice",
    email: "alice@example.com",
    password: "password789",
    isActive: true,
  },
  {
    userId: "4",
    firstName: "Bob",
    lastName: "Johnson",
    username: "bob",
    email: "bob@example.com",
    password: "passwordABC",
    isActive: false,
  },
  {
    userId: "5",
    firstName: "Emily",
    lastName: "Brown",
    username: "emily",
    email: "emily@example.com",
    password: "passwordDEF",
    isActive: true,
  },
  {
    userId: "6",
    firstName: "Michael",
    lastName: "Williams",
    username: "michael",
    email: "michael@example.com",
    password: "passwordGHI",
    isActive: false,
  },
  {
    userId: "7",
    firstName: "Sophia",
    lastName: "Jones",
    username: "sophia",
    email: "sophia@example.com",
    password: "passwordJKL",
    isActive: true,
  },
  {
    userId: "8",
    firstName: "William",
    lastName: "Brown",
    username: "william",
    email: "william@example.com",
    password: "passwordMNO",
    isActive: false,
  },
  {
    userId: "9",
    firstName: "Olivia",
    lastName: "Davis",
    username: "olivia",
    email: "olivia@example.com",
    password: "passwordPQR",
    isActive: true,
  },
  {
    userId: "10",
    firstName: "James",
    lastName: "Wilson",
    username: "james",
    email: "james@example.com",
    password: "passwordSTU",
    isActive: false,
  },
];
